version: 2
updates:
  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "pyformlang"
        versions:
          - ">=1.0.0"
